FROM golang:latest
RUN mkdir -p /go/src/github.com/dmmmd/scrumpoker
RUN ln -s /go/src/github.com/dmmmd/scrumpoker /scrumpoker
ADD main.go /scrumpoker
ADD go.* /scrumpoker/
ADD app /scrumpoker/app
WORKDIR /go/src/github.com/dmmmd/scrumpoker
ENV GOPATH /go
ENV GO111MODULE on
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /scrumpoker/scrumpoker .
CMD ["/scrumpoker/scrumpoker"]
