version: '3.3'
services:
  scrumpoker-db:
    image: mysql:5.7
    restart: always
    environment:
      # TODO move all configs out
      MYSQL_DATABASE: 'scrumpoker'
      MYSQL_USER: 'scrumpoker'
      MYSQL_PASSWORD: 'hYnRDFfWGdPCCG8BcKpZUvxWz6YaM3'
      MYSQL_ROOT_PASSWORD: 'TdfHCz;9skghgACcNKXrL*jTbaA9K7ss'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    command: --init-file /data/application/init.sql
    volumes:
      # Where our data will be persisted
      - scrumpoker-db-volume:/var/lib/mysql
      - ./db/init.sql:/data/application/init.sql
  scrumpoker-server:
    build:
      context: server
      dockerfile: Dockerfile.scratch
    ports:
      - "80:80"
    links:
      - scrumpoker-db:mysql
volumes:
  scrumpoker-db-volume:
