version: '3.3'
services:
  scrumpoker-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'scrumpoker'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'scrumpoker'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'hYnRDFfWGdPCCG8BcKpZUvxWz6YaM3'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'TdfHCz;9skghgACcNKXrL*jTbaA9K7ss'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      # Where our data will be persisted
      - scrumpoker-db-volume:/var/lib/mysql
  scrumpoker-server:
    build: server
    ports:
      - "80:80"
    links:
      - scrumpoker-db:mysql
# Names our volume
volumes:
  scrumpoker-db-volume:
